apiVersion: apps/v1
kind: Deployment
metadata: 
    name: product-deploy
spec:
    replicas: 1
    selector:
        matchLabels:
            app: productservice
    template:
        metadata:
            labels:
                app: productservice
        spec:
            containers:
                - name: productservice
                  image: ebrahimmohsen1/ecommerce